version: '2'

services:
    web:
        image: php:apache
        restart: unless-stopped
        volumes:
            - $PWD:/var/www
        ports:
            - 80:80
            - 443:443
        links:
            - mysql

    mysql:
        image: mysql:5.7
        restart: unless-stopped
        environment:
            - MYSQL_DATABASE=app
            - MYSQL_USER=app
            - MYSQL_PASSWORD=app
            - MYSQL_ROOT_PASSWORD=password
        ports:
            - 3306:3306
        volumes:
            - mysql:/var/lib/mysql

volumes:
    mysql:

